# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [3]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [4]:
# COMPLETE THIS TASK
np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [5]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [6]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [7]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [8]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[-0.46592661, -0.69332355,  2.02485866],
        [ 1.02662286, -0.03446931, -0.01456214],
        [-0.53074265, -0.30105687,  3.28326157]]),
 array([[0.16373815, 0.72449591, 0.28018142],
        [0.35468989, 0.43424794, 0.07515568],
        [0.83358563, 0.73224532, 0.72329963]]))

In [9]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.

A = np.random.randn(5,5)
B = 0.5*(A + A.T)
C = 0.5*(A - A.T)
A, B, C

(array([[ 0.1258779 ,  1.01153754,  0.19221262,  0.05172802, -0.00508775],
        [-0.95048096, -0.54119509, -0.54633358,  0.04521647, -1.13936907],
        [-0.58529437, -1.55029451,  0.84719444,  1.8977258 , -0.64052411],
        [ 0.29888609, -2.55698357, -1.48553482, -1.06548097,  0.03252679],
        [ 0.58149461, -0.69704742,  0.19297559, -0.30836869,  0.81573517]]),
 array([[ 0.1258779 ,  0.03052829, -0.19654087,  0.17530705,  0.28820343],
        [ 0.03052829, -0.54119509, -1.04831404, -1.25588355, -0.91820825],
        [-0.19654087, -1.04831404,  0.84719444,  0.20609549, -0.22377426],
        [ 0.17530705, -1.25588355,  0.20609549, -1.06548097, -0.13792095],
        [ 0.28820343, -0.91820825, -0.22377426, -0.13792095,  0.81573517]]),
 array([[ 0.        ,  0.98100925,  0.3887535 , -0.12357904, -0.29329118],
        [-0.98100925,  0.        ,  0.50198047,  1.30110002, -0.22116082],
        [-0.3887535 , -0.50198047,  0.        ,  1.69163031, -0.41674985],
        [ 0.12357904,

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [11]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [12]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [13]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences

# The '*' operator is a simple multiplication operator. When applied to arrays, it simply multiplies the components of the array.
A = np.array([[2,2],[4,4]])
B = np.array([[10,10],[20,20]])
print("Using the '*' operator on A and B yields:", A * B)

# To get the matrix product of two arrays, the '@' operator can be used
print("Using the '@' operator on A and B yields:", A @ B)

#Another way of going about this is using np.matmul. The benefit of this is that additional arguments can be fed into the function.

# The 'out' argument for instance allows the output of the calculated matrix product to be stored in a specific location.
C = np.zeros((2,2))
np.matmul(A, B, out=C)
print("Using np.matmul with 'out' argument yields:", C) #Here we are storing the output into previously defined C matrix

#Finally, the 'np.dot' function does a whole lot of things. For 1-D arrays, it takes the dot product. For 2-D arrays, it takes the matrix product. For scalars, it simply multiplies the two numbers
print("Using np.dot on A and B yields:", np.dot(A, B))

#For 1-D arrays
D = np.array([1,2])
E = np.array([2,3])
print("Using np.dot on D and E (two 1-D arrays) yields: ", np.dot(D, E))

#For two scalars
print("Using np.dot on two numbers, 5 and 6 yields: ", np.dot(5,6))

Using the '*' operator on A and B yields: [[20 20]
 [80 80]]
Using the '@' operator on A and B yields: [[ 60  60]
 [120 120]]
Using np.matmul with 'out' argument yields: [[ 60.  60.]
 [120. 120.]]
Using np.dot on A and B yields: [[ 60  60]
 [120 120]]
Using np.dot on D and E (two 1-D arrays) yields:  8
Using np.dot on two numbers, 5 and 6 yields:  30


## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [14]:
import math

In [15]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

846 ms ± 253 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [16]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
y_vec = np.sin(xs)

19 ms ± 4.69 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [17]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`

## From gemini:

The `%%timeit` magic command is an IPython feature used to measure the execution time of Python code. When placed at the beginning of a cell, it runs the code multiple times (typically 7 runs, with 1 to 100 loops per run depending on the code's speed) to get a statistically robust measurement. It then reports the mean and standard deviation of the execution times. This is incredibly useful for:

*   **Performance Comparison**: Comparing the speed of different approaches to the same problem (e.g., a loop-based solution vs. a vectorized NumPy solution).
*   **Optimization**: Identifying bottlenecks in your code.

There's also `%timeit` (with a single `%`), which is used for timing a single line of code, while `%%timeit` (with a double `%%`) is for timing an entire cell.

In [18]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator

#made up arrays to represent v and x for a harmonic oscillator:
k=1
x = np.array([1,2,3])
v = np.array([1,1,1])

#vectorized function:
def energy(x, v, k):
  T = 0.5 * k * x*x
  U = 0.5 * k * v*v
  return T+U

print(energy(x, v, k))

[1.  2.5 5. ]


## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [19]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [37]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?

for i in range(len(vals)):
  for q in range(len(vecs)):
    print( np.isclose(K@vecs[:, q], vals[i]*vecs[:, q])) #Uses the is.close function to see if variables are close to equal

#From this output it's clear that the first eigenvalue in vals corresponds to the first eigenvector in vecs, second to second, and third to third.


[ True  True  True]
[False  True False]
[False False False]
[False False False]
[ True  True  True]
[False False False]
[False False False]
[False  True False]
[ True  True  True]


## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [38]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [39]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [40]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [42]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.

print(vecs @ vecs.T)
print(vecs.T @ vecs)
#Diagonals are 1, non-diagonals are effectively zero. These are 2x2 identity matrices

[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]


In [43]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.

print(vals)
print(vecs.T @ K @ vecs)

[   0. 4900.]
[[ 3.94430453e-31  6.65719202e-14]
 [-8.69285906e-14  4.90000000e+03]]


In [45]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule

# As stated before the "The (quadratic) potential energy is: V = 0.5 * x.T @ K @ x"

print(0.5 * vecs.T @ K @ vecs)

#Shows that the two modes of this diatomic molecule can have an energy of 0 or an energy of 2.45E3

[[ 1.97215226e-31  3.32859601e-14]
 [-4.34642953e-14  2.45000000e+03]]
